# Config.toml

[settings]
retry_count = 3
timeout = 1000
log_level = "info"

[rpc_urls]
servers = [
    { url = "https://sepolia.drpc.org/", request_limit=1,current_limit=1 },
    { url = "https://polygon-rpc.com", request_limit=1,current_limit=1 },
    { url = "https://bsc-dataseed1.binance.org", request_limit=1,current_limit=1 },
    { url = "https://avalanche.public-rpc.com",request_limit=1,current_limit=1 },
    { url = "https://rpc.ftm.tools", request_limit=1 ,current_limit=1}
]
