[chains]

[chains.ethereum_sepolia]
rpc_urls = [
    { url = "https://sepolia.dfrpc.org/", request_limit = 5, current_limit = 5 },
    { url = "https://sepolia.infdura.io/v3/61a164b7aa39462cb0fc75f5b0ace269", request_limit = 5, current_limit = 5 },
    { url = "https://eth-sepolia.g.alchemy.com/v2/DumcaFO69U55TqhPevuTScTlDzxhvy0N", request_limit = 5, current_limit = 5 },
    { url = "https://sepolia.infura.io/v3/61a164b7aa39462cb0fc75f5b0ace269", request_limit = 5, current_limit = 5 },
]

[chains.polygon]
rpc_urls = [
    { url = "https://polygon-rpc.com", request_limit = 5, current_limit = 5 },
    { url = "https://another-polygon-rpc.com", request_limit = 5, current_limit = 5 }
]

[chains.bsc]
rpc_urls = [
    { url = "https://bsc-dataseed1.binance.org", request_limit = 5, current_limit = 5 },
    { url = "https://another-bsc-rpc.com", request_limit = 5, current_limit = 5 }
]

[chains.avalanche]
rpc_urls = [
    { url = "https://avalanche.public-rpc.com", request_limit = 5, current_limit = 5 },
    { url = "https://another-avalanche-rpc.com", request_limit = 5, current_limit = 5 }
]

[chains.fantom]
rpc_urls = [
    { url = "https://rpc.ftm.tools", request_limit = 5, current_limit = 5 },
    { url = "https://another-fantom-rpc.com", request_limit = 5, current_limit = 5 }
]
