[chains]

[chains.ethereum_sepolia]
rpc_urls = [
    { url = "https://sepolia.drpc.org/", request_limit = 5, current_limit = 5 },
    { url = "https://ethereum-sepolia-rpc.publicnode.com", request_limit = 5, current_limit = 5 },
    { url = "https://endpoints.omniatech.io/v1/eth/sepolia/public", request_limit = 5, current_limit = 5 },
    { url = "https://eth-sepolia.g.alchemy.com/v2/demo", request_limit = 5, current_limit = 5 },
    { url = "https://eth-sepolia.public.blastapi.io", request_limit = 5, current_limit = 5 },
    { url = "https://rpc-sepolia.rockx.com", request_limit = 5, current_limit = 5 },
    { url = "https://rpc2.sepolia.org", request_limit = 5, current_limit = 5 },
    { url = "https://eth-sepolia-public.unifra.io", request_limit = 5, current_limit = 5 },    
    { url = "https://eth-sepolia.g.alchemy.com/v2/DumcaFO69U55TqhPevuTScTlDzxhvy0N", request_limit = 5, current_limit = 5 }, 
    { url = "https://eth-sepolia.g.alchemy.com/v2/Vt-glQ2N0u8FIs-f0try1ghd7DAdYobc", request_limit = 5, current_limit = 5 }, 
]

[chains.base_sepolia]
rpc_urls = [
    { url = "https://base-sepolia.g.alchemy.com/v2/DumcaFO69U55TqhPevuTScTlDzxhvy0N", request_limit = 5, current_limit = 5 },
    { url = "https://base-sepolia.g.alchemy.com/v2/Vt-glQ2N0u8FIs-f0try1ghd7DAdYobc", request_limit = 5, current_limit = 5 },
]

[chains.arbitrum_sepolia]
rpc_urls = [
    { url = "https://arb-sepolia.g.alchemy.com/v2/DumcaFO69U55TqhPevuTScTlDzxhvy0N", request_limit = 5, current_limit = 5 },
    { url = "https://arb-sepolia.g.alchemy.com/v2/Vt-glQ2N0u8FIs-f0try1ghd7DAdYobc", request_limit = 5, current_limit = 5 },
]