[chains]

[chains.ethereum_sepolia]
rpc_urls = [
    { url = "https://eth-sepolia.g.alchemy.com/v2/DumcaFO69U55TqhPevuTScTlDzxhvy0N", request_limit = 5, current_limit = 5 },
    { url = "https://eth-sepolia.g.alchemy.com/v2/Vt-glQ2N0u8FIs-f0try1ghd7DAdYobc", request_limit = 5, current_limit = 5 },
    { url = "https://eth-sepolia.g.alchemy.com/v2/mRRENj5uQ1jqgfIIrtFZFzqUWQtU1lvH", request_limit = 5, current_limit = 5 },
    { url = "https://eth-sepolia.g.alchemy.com/v2/fjZ8CPTHtjIN989lInvYqljpGNqJTspg", request_limit = 5, current_limit = 5 },
    { url = "https://eth-sepolia.g.alchemy.com/v2/GvF-hcr7gTVjdoCbALH8WzMBjO5WysaQ", request_limit = 5, current_limit = 5 },

]

[chains.base_sepolia]
rpc_urls = [
    { url = "https://base-sepolia.g.alchemy.com/v2/DumcaFO69U55TqhPevuTScTlDzxhvy0N", request_limit = 5, current_limit = 5 },
    { url = "https://base-sepolia.g.alchemy.com/v2/Vt-glQ2N0u8FIs-f0try1ghd7DAdYobc", request_limit = 5, current_limit = 5 },
    { url = "https://base-sepolia.g.alchemy.com/v2/mRRENj5uQ1jqgfIIrtFZFzqUWQtU1lvH", request_limit = 5, current_limit = 5 },
    { url = "https://base-sepolia.g.alchemy.com/v2/fjZ8CPTHtjIN989lInvYqljpGNqJTspg", request_limit = 5, current_limit = 5 },
    { url = "https://base-sepolia.g.alchemy.com/v2/GvF-hcr7gTVjdoCbALH8WzMBjO5WysaQ", request_limit = 5, current_limit = 5 },
]

[chains.arbitrum_sepolia]
rpc_urls = [
    { url = "https://arb-sepolia.g.alchemy.com/v2/DumcaFO69U55TqhPevuTScTlDzxhvy0N", request_limit = 5, current_limit = 5 },
    { url = "https://arb-sepolia.g.alchemy.com/v2/Vt-glQ2N0u8FIs-f0try1ghd7DAdYobc", request_limit = 5, current_limit = 5 },
    { url = "https://arb-sepolia.g.alchemy.com/v2/mRRENj5uQ1jqgfIIrtFZFzqUWQtU1lvH", request_limit = 5, current_limit = 5 },
    { url = "https://arb-sepolia.g.alchemy.com/v2/fjZ8CPTHtjIN989lInvYqljpGNqJTspg", request_limit = 5, current_limit = 5 },
    { url = "https://arb-sepolia.g.alchemy.com/v2/GvF-hcr7gTVjdoCbALH8WzMBjO5WysaQ", request_limit = 5, current_limit = 5 },

]

[chains.berachain]
rpc_urls = [
    { url = "https://berachain-bartio.g.alchemy.com/v2/DumcaFO69U55TqhPevuTScTlDzxhvy0N", request_limit = 5, current_limit = 5 },
    { url = "https://berachain-bartio.g.alchemy.com/v2/Vt-glQ2N0u8FIs-f0try1ghd7DAdYobc", request_limit = 5, current_limit = 5 },
    { url = "https://berachain-bartio.g.alchemy.com/v2/mRRENj5uQ1jqgfIIrtFZFzqUWQtU1lvH", request_limit = 5, current_limit = 5 },
    { url = "https://berachain-bartio.g.alchemy.com/v2/fjZ8CPTHtjIN989lInvYqljpGNqJTspg", request_limit = 5, current_limit = 5 },
    { url = "https://berachain-bartio.g.alchemy.com/v2/GvF-hcr7gTVjdoCbALH8WzMBjO5WysaQ", request_limit = 5, current_limit = 5 },

]

[chains.bitcoin]
rpc_urls = [
    { url = "https://rpc.ankr.com/btc_signet/2a8161e0d7bc03b1d7198e539c94b34481ad94443090a041314aedc2b29ea17b", request_limit = 5, current_limit = 5 },
    { url = "https://rpc.ankr.com/btc_signet/bc0fb296415993c1eccfc983e9b8f4881272efa66f8f92fa916ea053b2bb768c", request_limit = 5, current_limit = 5 },
]
