[chains]

[chains.ethereum_sepolia]
rpc_urls = [
    { url = "https://eth-sepolia.g.alchemy.com/v2/Vt-glQ2N0u8FIs-f0try1ghd7DAdYobc", request_limit = 20, current_limit = 20 },
    { url = "https://eth-sepolia.g.alchemy.com/v2/DumcaFO69U55TqhPevuTScTlDzxhvy0N", request_limit = 20, current_limit = 20 },
    { url = "https://1rpc.io/sepolia", request_limit = 20, current_limit = 20 },
    { url = "https://endpoints.omniatech.io/v1/eth/sepolia/public", request_limit = 20, current_limit = 20 },
    { url = "https://ethereum-sepolia-rpc.publicnode.com", request_limit = 20, current_limit = 20 },
    { url = "https://eth-sepolia.g.alchemy.com/v2/mRRENj5uQ1jqgfIIrtFZFzqUWQtU1lvH", request_limit = 20, current_limit = 20 },
    { url = "https://eth-sepolia.g.alchemy.com/v2/fjZ8CPTHtjIN989lInvYqljpGNqJTspg", request_limit = 20, current_limit = 20 },
    { url = "https://eth-sepolia.g.alchemy.com/v2/GvF-hcr7gTVjdoCbALH8WzMBjO5WysaQ", request_limit = 20, current_limit = 20 },
]

[chains.base_sepolia]
rpc_urls = [
    { url = "https://base-sepolia.g.alchemy.com/v2/DumcaFO69U55TqhPevuTScTlDzxhvy0N", request_limit = 20, current_limit = 20 },
    { url = "https://base-sepolia.g.alchemy.com/v2/Vt-glQ2N0u8FIs-f0try1ghd7DAdYobc", request_limit = 20, current_limit = 20 },
    { url = "https://base-sepolia.g.alchemy.com/v2/mRRENj5uQ1jqgfIIrtFZFzqUWQtU1lvH", request_limit = 20, current_limit = 20 },
    { url = "https://base-sepolia.g.alchemy.com/v2/fjZ8CPTHtjIN989lInvYqljpGNqJTspg", request_limit = 20, current_limit = 20 },
    { url = "https://base-sepolia.g.alchemy.com/v2/GvF-hcr7gTVjdoCbALH8WzMBjO5WysaQ", request_limit = 20, current_limit = 20 },
]

[chains.arbitrum_sepolia]
rpc_urls = [
    { url = "https://arb-sepolia.g.alchemy.com/v2/DumcaFO69U55TqhPevuTScTlDzxhvy0N", request_limit = 20, current_limit = 20 },
    { url = "https://arb-sepolia.g.alchemy.com/v2/Vt-glQ2N0u8FIs-f0try1ghd7DAdYobc", request_limit = 20, current_limit = 20 },
    { url = "https://arb-sepolia.g.alchemy.com/v2/mRRENj5uQ1jqgfIIrtFZFzqUWQtU1lvH", request_limit = 20, current_limit = 20 },
    { url = "https://arb-sepolia.g.alchemy.com/v2/fjZ8CPTHtjIN989lInvYqljpGNqJTspg", request_limit = 20, current_limit = 20 },
    { url = "https://arb-sepolia.g.alchemy.com/v2/GvF-hcr7gTVjdoCbALH8WzMBjO5WysaQ", request_limit = 20, current_limit = 20 },

]

[chains.berachain]
rpc_urls = [
    { url = "https://berachain-bartio.g.alchemy.com/v2/DumcaFO69U55TqhPevuTScTlDzxhvy0N", request_limit = 20, current_limit = 20 },
    { url = "https://berachain-bartio.g.alchemy.com/v2/Vt-glQ2N0u8FIs-f0try1ghd7DAdYobc", request_limit = 20, current_limit = 20 },
    { url = "https://berachain-bartio.g.alchemy.com/v2/mRRENj5uQ1jqgfIIrtFZFzqUWQtU1lvH", request_limit = 20, current_limit = 20 },
    { url = "https://berachain-bartio.g.alchemy.com/v2/fjZ8CPTHtjIN989lInvYqljpGNqJTspg", request_limit = 20, current_limit = 20 },
    { url = "https://berachain-bartio.g.alchemy.com/v2/GvF-hcr7gTVjdoCbALH8WzMBjO5WysaQ", request_limit = 20, current_limit = 20 },

]

[chains.bitcoin]
rpc_urls = [
    { url = "https://rpc.ankr.com/btc_signet/2a8161e0d7bc03b1d7198e539c94b34481ad94443090a041314aedc2b29ea17b", request_limit = 20, current_limit = 20 },
    { url = "https://rpc.ankr.com/btc_signet/bc0fb296415993c1eccfc983e9b8f4881272efa66f8f92fa916ea053b2bb768c", request_limit = 20, current_limit = 20 },
]

[chains.monad_testnet]
rpc_urls = [
    { url = "https://rpc.monad-testnet.category.xyz/rpc/SPa4TbSgMJxz5ywmzYvvc9O5nkAVGTgOcsi7yErG", request_limit = 20, current_limit = 20 },
]


[chains.base]
rpc_urls = [
    { url = "https://base.llamarpc.com", request_limit = 20, current_limit = 20 },
    { url = "https://base.meowrpc.com", request_limit = 20, current_limit = 20 },
    { url = "https://base-pokt.nodies.app", request_limit = 20, current_limit = 20 },
    { url = "https://1rpc.io/base", request_limit = 20, current_limit = 20 },
    { url = "https://endpoints.omniatech.io/v1/base/mainnet/public", request_limit = 20, current_limit = 20 },
    { url = "https://base-rpc.publicnode.com", request_limit = 20, current_limit = 20 },
    { url = "https://mainnet.base.org", request_limit = 20, current_limit = 20 },
    { url = "https://developer-access-mainnet.base.org", request_limit = 20, current_limit = 20 },
    { url = "https://1rpc.io/base", request_limit = 20, current_limit = 20 },
]

[chains.arbitrum]
rpc_urls = [
    { url = "https://endpoints.omniatech.io/v1/arbitrum/one/public", request_limit = 20, current_limit = 20 },
    { url = "https://arbitrum.meowrpc.com", request_limit = 20, current_limit = 20 },
    { url = "https://arbitrum.llamarpc.com", request_limit = 20, current_limit = 20 },
    { url = "https://arb-pokt.nodies.app", request_limit = 20, current_limit = 20 },
    { url = "https://1rpc.io/arb", request_limit = 20, current_limit = 20 },
    { url = "https://arb-mainnet.g.alchemy.com/v2/demo", request_limit = 20, current_limit = 20 },
    { url = "https://rpc.ankr.com/arbitrum", request_limit = 20, current_limit = 20 },
    { url = "https://arb1.arbitrum.io/rpc", request_limit = 20, current_limit = 20 },
    { url = "https://arbitrum-one.public.blastapi.io", request_limit = 20, current_limit = 20 },
    { url = "https://arbitrum.blockpi.network/v1/rpc/public", request_limit = 20, current_limit = 20 },
    { url = "https://arb1.croswap.com/rpc", request_limit = 20, current_limit = 20 },
    { url = "https://endpoints.omniatech.io/v1/arbitrum/one/public", request_limit = 20, current_limit = 20 },
    { url = "https://arbitrum.api.onfinality.io/public", request_limit = 20, current_limit = 20 },
    { url = "https://arb-mainnet-public.unifra.io", request_limit = 20, current_limit = 20 },
]


[chains.ethereum]
rpc_urls = [
    { url = "https://1rpc.io/eth", request_limit = 20, current_limit = 20 },
    { url = "https://eth-mainnet.g.alchemy.com/v2/demo", request_limit = 20, current_limit = 20 },
    { url = "https://rpc.ankr.com/eth", request_limit = 20, current_limit = 20 },
    { url = "https://ethereum.blockpi.network/v1/rpc/public", request_limit = 20, current_limit = 20 },
    { url = "https://eth-mainnet.public.blastapi.io", request_limit = 20, current_limit = 20 },
    { url = "https://uk.rpc.blxrbdn.com", request_limit = 20, current_limit = 20 },
    { url = "https://eth.rpc.blxrbdn.com", request_limit = 20, current_limit = 20 },
    { url = "https://virginia.rpc.blxrbdn.com", request_limit = 20, current_limit = 20 },
    { url = "https://singapore.rpc.blxrbdn.com", request_limit = 20, current_limit = 20 },
    { url = "https://rpc.builder0x69.io", request_limit = 20, current_limit = 20 },
    { url = "https://cloudflare-eth.com", request_limit = 20, current_limit = 20 },
    { url = "https://rpc.flashbots.net", request_limit = 20, current_limit = 20 },
    { url = "https://ethereumnodelight.app.runonflux.io", request_limit = 20, current_limit = 20 },
    { url = "https://core.gashawk.io/rpc", request_limit = 20, current_limit = 20 },
    { url = "https://main-light.eth.linkpool.io", request_limit = 20, current_limit = 20 },
    { url = "https://eth.llamarpc.com", request_limit = 20, current_limit = 20 },
    { url = "https://rpc.mevblocker.io", request_limit = 20, current_limit = 20 },
]
