# Config.toml

[settings]
retry_count = 3  
timeout = 5000   
log_level = "info"  

[rpc_urls]

[[rpc_urls.servers]]
url = "https://eth-mainnet.g.alchemy.com/v2/demo"
weight = 20
chain_id = "1"  
max_connections = 100


[[rpc_urls.servers]]
url = "https://polygon-rpc.com"
weight = 15
chain_id = "137"  
max_connections = 150


[[rpc_urls.servers]]
url = "https://bsc-dataseed1.binance.org"
weight = 25
chain_id = "56"  
max_connections = 200


[[rpc_urls.servers]]
url = "https://avalanche.public-rpc.com"
weight = 20
chain_id = "43114" 
max_connections = 150


[[rpc_urls.servers]]
url = "https://rpc.ftm.tools"
weight = 20
chain_id = "250"  
max_connections = 150
